version: "3"

services:
  client:
    image: cadubentzen/multi-client
    mem_limit: 128m

  api:
    image: cadubentzen/multi-server
    mem_limit: 128m
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGHOST: $PGHOST
      PGDATABASE: $PGPASSWORD
      PGPORT: $PGPORT

  worker:
    image: cadubentzen/multi-worker
    mem_limit: 128m
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT

  nginx:
    image: cadubentzen/multi-nginx
    mem_limit: 128m
    depends_on:
      - api
      - client
    ports:
      - 80:80
