name: Docker Build, Test & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-client:
    runs-on: ubuntu-latest
    name: Test Client
    steps:
    - uses: actions/checkout@v2
    - name: Build the Client Docker image
      run: docker build -t cadubentzen/react-test -f ./client/Dockerfile.dev ./client
    - name: Test Client
      run: docker run -e CI=true cadubentzen/react-test npm run test
      
  prod-build-and-publish:
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        component: [client, nginx, server, worker]
    concurrency: ${{ matrix.component }}
    runs-on: ubuntu-latest
    name: Build and publish prod ${{ matrix.component }}
    needs: test-client
    steps:
    - uses: actions/checkout@v2
    - name: Build production image for ${{ matrix.component }}
      run: docker build -t cadubentzen/multi-${{ matrix.component }} ./${{ matrix.component }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish ${{ matrix.component }}
      run: docker push cadubentzen/${{ matrix.component }}
    
